### ISSUE TITLE
Game load crash: `IllegalArgumentException: Bad CraftTweaker item ingredient: <ore:dustSkyStone>`

### ISSUE THREAD

**Issue by Krutoy242** [phantamanta44/Lazy-AE2#60]
For testing purposes i removed TConEvo from my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended). Now, after 2-3 minutes of game loading I got crash from `Lazy AE2`:

```ruby
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lazy AE2 (threng)
Caused by: java.lang.IllegalArgumentException: Bad CraftTweaker item ingredient: <ore:dustSkyStone>
    at io.github.phantamanta44.threng.integration.crafttweaker.CrTUtils.matchInputItemStack(CrTUtils.java:27)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at io.github.phantamanta44.threng.integration.crafttweaker.CrTClassAggregator.lambda$addRecipe$0(CrTClassAggregator.java:31)
```

I have many tweaked function in my .zs code, but there is two with `dustSkyStone` ingredient in it:

```zs
// scripts/mods/endreborn.zs
mods.threng.Aggregator.addRecipe(<threng:material>, <endreborn:item_ingot_wolframium>, <threng:material:1>, <ore:dustSkyStone>);

// scripts/mods/lazyae.zs
mods.threng.Aggregator.addRecipe(<threng:material:5>, <biomesoplenty:terrestrial_artifact>, <ore:gemAmethyst>, <ore:dustSkyStone>);

```

### [debug.log](https://github.com/phantamanta44/Lazy-AE2/files/14623011/debug.log)

Changing `<ore:dustSkyStone>` to `<appliedenergistics2:material:45>` (actual item representation of dust) fixes the issue. This sounds odd, since in game, `dustSkyStone` ore is not empty and have exactly this item in it.

**Comment by Krutoy242** [comment]
Accidentally closed issue with commit comment. Issue is still actual.
